[project]
name = "beem-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch==1.4.0",
    "transformers==2.5.1",
    "numpy",
    "tqdm",
    "tensorboard",
    "scikit-learn",
    "scipy",
]
